# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.0
_src_path: /home/dab/Projects/ha-hacs-template
author_name: Dabentz
documentation_url: https://github.com/Dabentz/ha-immich-browser
integration_type: service
iot_class: local_polling
issue_tracker_url: https://github.com/Dabentz/ha-immich-browser/issues
project_description: Browse your Immich photo library from Home Assistant dashboards.
project_domain: immich_browser
project_name: Immich Browser
use_multi_step_config_flow: false
use_secondary_coordinator: true
use_services: false
use_websocket: true
version: 0.1.0
